from augment.base import AugmentationStep
from augment.augmenter import run_augmentation
from augment.augmenter import run_augmentation_old
from augment.example import ExampleAugmentationStep
from augment.trafo101 import Trafo101Step
from augment.trafo5 import Trafo5Step
from augment.trafo82 import Trafo82Step
from augment.trafo3 import Trafo3Step
from augment.trafo39 import Trafo39Step
from augment.trafo40 import Trafo40Step
from augment.trafo90 import Trafo90Step
from augment.trafo103 import Trafo103Step
from augment.trafo33 import Trafo33Step
from augment.trafo58 import Trafo58Step
from augment.trafo100 import Trafo100Step
from augment.filter9 import Filter9Step
from augment.filter10 import Filter10Step
from augment.filter19 import Filter19Step
from augment.trafo8 import Trafo8Step